# tasks file
---
- name: include variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "_{{ ansible_distribution_release }}.yml"
    - "_{{ ansible_distribution | lower }}.yml"
    - _default.yml
  tags:
    - configuration
    - updatedb
    - updatedb-include-variables

- name: install
  ansible.builtin.apt:
    name: "{{ updatedb_dependencies }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  tags:
    - configuration
    - updatedb
    - updatedb-install

- name: configure /etc/updatedb.conf
  ansible.builtin.template:
    src: etc/updatedb.conf.j2
    dest: /etc/updatedb.conf
    owner: root
    group: root
    mode: '0644'
    backup: true
  notify: update updatedb
  tags:
    - configuration
    - updatedb
    - updatedb-configuration
