# tasks file for updatedb
---
- name: install
  apt:
    name: mlocate
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  tags:
    - configuration
    - updatedb
    - updatedb-install

- name: configure /etc/updatedb.conf
  template:
    src: etc/updatedb.conf.j2
    dest: /etc/updatedb.conf
    owner: root
    group: root
    mode: 0644
    backup: true
  notify: update updatedb
  tags:
    - configuration
    - updatedb
    - updatedb-configuration
