# tasks file
---
- name: install
  apt:
    name: "{{ updatedb_dependencies }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  tags:
    - configuration
    - updatedb
    - updatedb-install

- name: configure /etc/updatedb.conf
  template:
    src: etc/updatedb.conf.j2
    dest: /etc/updatedb.conf
    owner: root
    group: root
    mode: 0644
    backup: true
  notify: update updatedb
  tags:
    - configuration
    - updatedb
    - updatedb-configuration

- name: register path stat mlocate_disabled_stat
  stat: path=/etc/cron.daily/mlocate.disabled
  register: mlocate_disabled_stat
- name: Enable mlocate in daily cron
  command: mv /etc/cron.daily/mlocate.disabled /etc/cron.daily/mlocate
  when: mlocate_disabled_stat.stat.exists
  tags:
  - configuration
  - updatedb
  - updatedb-configuration